services:
  - type: web
    name: hackrx-webhook
    env: python
    region: oregon
    plan: free
    runtime: python
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:main --host=0.0.0.0 --port=8000
